import telebot
from src.config_private import TELEGRAM_TOKEN

CRYPTO = "BTC,ETH,SOL,ADA,KAS,FTM,VET,MATIC,STARK,LINK,ATOM,AXL,AVAX,ICP,EGLD,DYDX,CKB,OCEAN,AGIX,TAO,CHZ,SAND,GALA,DOGE,SHIB,PEPE,FLOKI"
CURRENCY = "USD"

bot = telebot.TeleBot(TELEGRAM_TOKEN)