import telebot
from src.config_private import TELEGRAM_TOKEN

CRYPTO = "BTC,ETH,SOL,ADA,KAS,FTM,VET,MATIC,STRK,LINK,ATOM,AXL,AVAX,ICP,EGLD,DYDX,CKB,OCEAN,AGIX,TAO,CHZ,SAND,GALA,CLORE,0x0"
CURRENCY = "USD"

bot = telebot.TeleBot(TELEGRAM_TOKEN)



